import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import LoginButton from './loginButton'
import LogoutButton from './logoutButton'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="ko">
      <body>
        <div className="navbar">
          <div>
            <Link href="/" className="logo">dailyforum</Link>
            <Link href="/list">List</Link>
          </div>
          <div>
            {session !== null ?
              <LogoutButton session={session} /> : <LoginButton session />
            }
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
